name: Release
  
on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Fake build
        run: echo lmao > kek.txt
      - name: Semantic Release
        run: |
          echo npx semantic-release
          echo "Release job 🚀!"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
