name: Release
  
on:
  push:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Fake build
        run: echo lmao > kek.txt
      - name: Semantic Release
        run: |
          npm -g install @semantic-release/git semantic-release semantic-release-github-actions-tags
          npx semantic-release
          echo "Release job 🚀!"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
